import 'package:flutter/foundation.dart';

import '../../domain/airports.dart';

/// Country-keyed travel intel: ISO alpha-2 code, currency, primary
/// visa policy + customs cap, time zone offset against UTC, calling
/// code. Used by the Trip detail screen to derive trip-aware values
/// for the Visa / Currency / Time cards instead of hard-coding a
/// single destination (the legacy version was always Schengen/JP).
///
/// Stays inside the app — no network call. Curated to cover every
/// airport country we ship in `domain/airports.dart`.
@immutable
class CountryProfile {
  const CountryProfile({
    required this.country,
    required this.iso2,
    required this.currency,
    required this.currencySymbol,
    required this.utcOffsetHours,
    required this.callingCode,
    required this.visaPolicy,
    required this.stayAllowed,
    required this.passportValidity,
    required this.onwardTicket,
    required this.customsCap,
  });

  /// Country name (matches the `country` field on `Airport`).
  final String country;
  final String iso2;
  final String currency;
  final String currencySymbol;
  final double utcOffsetHours;
  final String callingCode;

  /// Short label like 'VISA-FREE' / 'eVISA' / 'VISA REQ' rendered as a chip.
  final String visaPolicy;
  final String stayAllowed;
  final String passportValidity;
  final String onwardTicket;
  final String customsCap;
}

class CountryIntel {
  CountryIntel._();

  static const Map<String, CountryProfile> _byCountry = {
    'United States': CountryProfile(
      country: 'United States',
      iso2: 'US',
      currency: 'USD',
      currencySymbol: '\$',
      utcOffsetHours: -5,
      callingCode: '+1',
      visaPolicy: 'ESTA',
      stayAllowed: '90 days under VWP',
      passportValidity: 'Valid for stay',
      onwardTicket: 'Required',
      customsCap: 'Declare > \$10,000',
    ),
    'Canada': CountryProfile(
      country: 'Canada',
      iso2: 'CA',
      currency: 'CAD',
      currencySymbol: '\$',
      utcOffsetHours: -5,
      callingCode: '+1',
      visaPolicy: 'eTA',
      stayAllowed: '180 days',
      passportValidity: 'Valid for stay',
      onwardTicket: 'Recommended',
      customsCap: 'Declare > CA\$10,000',
    ),
    'Mexico': CountryProfile(
      country: 'Mexico',
      iso2: 'MX',
      currency: 'MXN',
      currencySymbol: '\$',
      utcOffsetHours: -6,
      callingCode: '+52',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '180 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Recommended',
      customsCap: 'Declare > \$10,000',
    ),
    'United Kingdom': CountryProfile(
      country: 'United Kingdom',
      iso2: 'GB',
      currency: 'GBP',
      currencySymbol: '\u00a3',
      utcOffsetHours: 0,
      callingCode: '+44',
      visaPolicy: 'ETA',
      stayAllowed: '6 months',
      passportValidity: 'Valid for stay',
      onwardTicket: 'Recommended',
      customsCap: 'Declare > \u00a310,000',
    ),
    'France': CountryProfile(
      country: 'France',
      iso2: 'FR',
      currency: 'EUR',
      currencySymbol: '\u20ac',
      utcOffsetHours: 1,
      callingCode: '+33',
      visaPolicy: 'SCHENGEN',
      stayAllowed: '90 / 180 days',
      passportValidity: '3 months beyond exit',
      onwardTicket: 'Required',
      customsCap: 'Declare > \u20ac10,000',
    ),
    'Germany': CountryProfile(
      country: 'Germany',
      iso2: 'DE',
      currency: 'EUR',
      currencySymbol: '\u20ac',
      utcOffsetHours: 1,
      callingCode: '+49',
      visaPolicy: 'SCHENGEN',
      stayAllowed: '90 / 180 days',
      passportValidity: '3 months beyond exit',
      onwardTicket: 'Required',
      customsCap: 'Declare > \u20ac10,000',
    ),
    'Netherlands': CountryProfile(
      country: 'Netherlands',
      iso2: 'NL',
      currency: 'EUR',
      currencySymbol: '\u20ac',
      utcOffsetHours: 1,
      callingCode: '+31',
      visaPolicy: 'SCHENGEN',
      stayAllowed: '90 / 180 days',
      passportValidity: '3 months beyond exit',
      onwardTicket: 'Required',
      customsCap: 'Declare > \u20ac10,000',
    ),
    'Spain': CountryProfile(
      country: 'Spain',
      iso2: 'ES',
      currency: 'EUR',
      currencySymbol: '\u20ac',
      utcOffsetHours: 1,
      callingCode: '+34',
      visaPolicy: 'SCHENGEN',
      stayAllowed: '90 / 180 days',
      passportValidity: '3 months beyond exit',
      onwardTicket: 'Required',
      customsCap: 'Declare > \u20ac10,000',
    ),
    'Switzerland': CountryProfile(
      country: 'Switzerland',
      iso2: 'CH',
      currency: 'CHF',
      currencySymbol: 'CHF',
      utcOffsetHours: 1,
      callingCode: '+41',
      visaPolicy: 'SCHENGEN',
      stayAllowed: '90 / 180 days',
      passportValidity: '3 months beyond exit',
      onwardTicket: 'Required',
      customsCap: 'Declare > CHF 10,000',
    ),
    'Turkey': CountryProfile(
      country: 'Turkey',
      iso2: 'TR',
      currency: 'TRY',
      currencySymbol: '\u20ba',
      utcOffsetHours: 3,
      callingCode: '+90',
      visaPolicy: 'eVISA',
      stayAllowed: '90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Recommended',
      customsCap: 'Declare > \u20ac10,000',
    ),
    'Singapore': CountryProfile(
      country: 'Singapore',
      iso2: 'SG',
      currency: 'SGD',
      currencySymbol: 'S\$',
      utcOffsetHours: 8,
      callingCode: '+65',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > S\$20,000',
    ),
    'Japan': CountryProfile(
      country: 'Japan',
      iso2: 'JP',
      currency: 'JPY',
      currencySymbol: '\u00a5',
      utcOffsetHours: 9,
      callingCode: '+81',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '90 days',
      passportValidity: 'Valid for stay',
      onwardTicket: 'Required',
      customsCap: 'Declare > \u00a51,000,000',
    ),
    'China': CountryProfile(
      country: 'China',
      iso2: 'CN',
      currency: 'CNY',
      currencySymbol: '\u00a5',
      utcOffsetHours: 8,
      callingCode: '+86',
      visaPolicy: 'VISA REQ',
      stayAllowed: 'Per visa class',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > US\$5,000',
    ),
    'South Korea': CountryProfile(
      country: 'South Korea',
      iso2: 'KR',
      currency: 'KRW',
      currencySymbol: '\u20a9',
      utcOffsetHours: 9,
      callingCode: '+82',
      visaPolicy: 'K-ETA',
      stayAllowed: '90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > US\$10,000',
    ),
    'Thailand': CountryProfile(
      country: 'Thailand',
      iso2: 'TH',
      currency: 'THB',
      currencySymbol: '\u0e3f',
      utcOffsetHours: 7,
      callingCode: '+66',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '60 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > US\$20,000',
    ),
    'India': CountryProfile(
      country: 'India',
      iso2: 'IN',
      currency: 'INR',
      currencySymbol: '\u20b9',
      utcOffsetHours: 5.5,
      callingCode: '+91',
      visaPolicy: 'eVISA',
      stayAllowed: 'Per visa class',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > US\$5,000',
    ),
    'Malaysia': CountryProfile(
      country: 'Malaysia',
      iso2: 'MY',
      currency: 'MYR',
      currencySymbol: 'RM',
      utcOffsetHours: 8,
      callingCode: '+60',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > RM30,000',
    ),
    'United Arab Emirates': CountryProfile(
      country: 'United Arab Emirates',
      iso2: 'AE',
      currency: 'AED',
      currencySymbol: 'AED',
      utcOffsetHours: 4,
      callingCode: '+971',
      visaPolicy: 'VISA ON ARRIVAL',
      stayAllowed: '30 / 90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > AED 60,000',
    ),
    'Australia': CountryProfile(
      country: 'Australia',
      iso2: 'AU',
      currency: 'AUD',
      currencySymbol: '\$',
      utcOffsetHours: 10,
      callingCode: '+61',
      visaPolicy: 'eVISA',
      stayAllowed: '90 days under ETA',
      passportValidity: 'Valid for stay',
      onwardTicket: 'Required',
      customsCap: 'Declare > AU\$10,000',
    ),
    'New Zealand': CountryProfile(
      country: 'New Zealand',
      iso2: 'NZ',
      currency: 'NZD',
      currencySymbol: '\$',
      utcOffsetHours: 12,
      callingCode: '+64',
      visaPolicy: 'NZeTA',
      stayAllowed: '90 days',
      passportValidity: '3 months beyond exit',
      onwardTicket: 'Required',
      customsCap: 'Declare > NZ\$10,000',
    ),
    'Brazil': CountryProfile(
      country: 'Brazil',
      iso2: 'BR',
      currency: 'BRL',
      currencySymbol: 'R\$',
      utcOffsetHours: -3,
      callingCode: '+55',
      visaPolicy: 'eVISA',
      stayAllowed: '90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Recommended',
      customsCap: 'Declare > US\$10,000',
    ),
    'Argentina': CountryProfile(
      country: 'Argentina',
      iso2: 'AR',
      currency: 'ARS',
      currencySymbol: '\$',
      utcOffsetHours: -3,
      callingCode: '+54',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Recommended',
      customsCap: 'Declare > US\$10,000',
    ),
    'Peru': CountryProfile(
      country: 'Peru',
      iso2: 'PE',
      currency: 'PEN',
      currencySymbol: 'S/',
      utcOffsetHours: -5,
      callingCode: '+51',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '183 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > US\$10,000',
    ),
    'South Africa': CountryProfile(
      country: 'South Africa',
      iso2: 'ZA',
      currency: 'ZAR',
      currencySymbol: 'R',
      utcOffsetHours: 2,
      callingCode: '+27',
      visaPolicy: 'VISA-FREE',
      stayAllowed: '90 days',
      passportValidity: '30 days beyond exit',
      onwardTicket: 'Required',
      customsCap: 'Declare > R 25,000',
    ),
    'Egypt': CountryProfile(
      country: 'Egypt',
      iso2: 'EG',
      currency: 'EGP',
      currencySymbol: 'E\u00a3',
      utcOffsetHours: 2,
      callingCode: '+20',
      visaPolicy: 'VISA ON ARRIVAL',
      stayAllowed: '30 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > US\$10,000',
    ),
    'Kenya': CountryProfile(
      country: 'Kenya',
      iso2: 'KE',
      currency: 'KES',
      currencySymbol: 'KSh',
      utcOffsetHours: 3,
      callingCode: '+254',
      visaPolicy: 'eVISA',
      stayAllowed: '90 days',
      passportValidity: '6 months beyond entry',
      onwardTicket: 'Required',
      customsCap: 'Declare > US\$10,000',
    ),
  };

  static const CountryProfile _fallback = CountryProfile(
    country: 'Destination',
    iso2: 'XX',
    currency: 'USD',
    currencySymbol: '\$',
    utcOffsetHours: 0,
    callingCode: '+',
    visaPolicy: 'VERIFY',
    stayAllowed: 'Check requirements',
    passportValidity: '6 months beyond entry',
    onwardTicket: 'Verify',
    customsCap: 'Declare > US\$10,000',
  );

  /// Resolve a country profile for a given destination IATA. Falls
  /// back to a neutral profile so callers never null out the card.
  static CountryProfile fromIata(String? iata) {
    final ap = getAirport(iata);
    if (ap == null) return _fallback;
    return _byCountry[ap.country] ?? _fallback;
  }
}
